export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST";
export const CURRENT_USER_RESPONSE = "CURRENT_USER_RESPONSE";
export const CURRENT_USER_ERROR = "CURRENT_USER_ERROR";
export const CURRENT_USER_CLEAR = "CURRENT_USER_CLEAR";
